repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: check-ast
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: debug-statements
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    - id: no-commit-to-branch
      args:
          - "--branch"
          - "main"
-   repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        args: [--config=server/setup.cfg]
        additional_dependencies: [flake8-typing-imports==1.10.1, flake8-tidy-imports]
-   repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    -   id: black
        args: [--line-length=79]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
    -   id: reorder-python-imports
        args: [--py3-plus]
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.25.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        args: [--config-file=src/setup.cfg]
